spring:
  application: blog-self
  datasource:
    url: jdbc:mysql:///blog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: -1ms
        min-idle: 0
    timeout: 5000

mybatis:
  configuration:    # 指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true    # 	是否开启驼峰命名自动映射
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8081
jwt:
  header: Authorization
  expire: 604800
  secret: c15be9a15a0a238084e0c5a846f3a7b4